-- MySQL Script generated by MySQL Workbench
-- Wed May 20 03:39:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pc_master
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pc_master
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pc_master` DEFAULT CHARACTER SET utf8;
USE `pc_master`;

-- -----------------------------------------------------
-- Table `pc_master`.`component_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_master`.`component_type`
(
    `id`          INT          NOT NULL AUTO_INCREMENT,
    `name`        VARCHAR(64)  NOT NULL,
    `description` VARCHAR(512) NULL,
    `image_url`   VARCHAR(256) NULL,
    `required`    TINYINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pc_master`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_master`.`supplier`
(
    `id`        INT          NOT NULL AUTO_INCREMENT,
    `name`      VARCHAR(64)  NOT NULL,
    `image_url` VARCHAR(256) NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pc_master`.`component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_master`.`component`
(
    `id`                INT          NOT NULL AUTO_INCREMENT,
    `name`              VARCHAR(45)  NOT NULL,
    `price`             INT          NOT NULL,
    `component_type_id` INT          NOT NULL,
    `supplier_id`       INT          NOT NULL,
    `image_url`         VARCHAR(256) NULL,
    PRIMARY KEY (`id`, `component_type_id`, `supplier_id`),
    INDEX `fk_component_type_has_producer_producer1_idx` (`supplier_id` ASC),
    INDEX `fk_component_type_has_producer_component_type_idx` (`component_type_id` ASC),
    CONSTRAINT `fk_component_type_has_producer_component_type`
        FOREIGN KEY (`component_type_id`)
            REFERENCES `pc_master`.`component_type` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_component_type_has_producer_producer1`
        FOREIGN KEY (`supplier_id`)
            REFERENCES `pc_master`.`supplier` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pc_master`.`account_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_master`.`account_type`
(
    `id`   INT         NOT NULL AUTO_INCREMENT,
    `type` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `type_UNIQUE` (`type` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pc_master`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_master`.`account`
(
    `id`              INT          NOT NULL AUTO_INCREMENT,
    `first_name`      VARCHAR(64)  NOT NULL,
    `last_name`       VARCHAR(64)  NOT NULL,
    `middle_name`     VARCHAR(64)  NOT NULL,
    `username`        VARCHAR(64)  NOT NULL,
    `password`        VARCHAR(256) NOT NULL,
    `account_type_id` INT          NULL,
    `token`           VARCHAR(256) NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_person_account_type1_idx` (`account_type_id` ASC),
    CONSTRAINT `fk_person_account_type1`
        FOREIGN KEY (`account_type_id`)
            REFERENCES `pc_master`.`account_type` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pc_master`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_master`.`order`
(
    `id`         INT      NOT NULL AUTO_INCREMENT,
    `client_id`  INT      NOT NULL,
    `order_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`, `client_id`),
    INDEX `fk_order_account1_idx` (`client_id` ASC),
    CONSTRAINT `fk_order_account1`
        FOREIGN KEY (`client_id`)
            REFERENCES `pc_master`.`account` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pc_master`.`order_component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_master`.`order_component`
(
    `order_id`     INT NOT NULL,
    `component_id` INT NOT NULL,
    `price`        INT NOT NULL,
    PRIMARY KEY (`order_id`, `component_id`),
    INDEX `fk_component_has_order_order1_idx` (`order_id` ASC),
    INDEX `fk_component_has_order_component1_idx` (`component_id` ASC),
    CONSTRAINT `fk_component_has_order_component1`
        FOREIGN KEY (`component_id`)
            REFERENCES `pc_master`.`component` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_component_has_order_order1`
        FOREIGN KEY (`order_id`)
            REFERENCES `pc_master`.`order` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
